version: '3.8'

services:
  django:
    image: netbaan-sjarif-interview
    container_name: django
    build:
      context: ./code
      dockerfile: Dockerfile
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./code:/code/
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
      - DEBUG=True
      - SECRET_KEY=sdlkfhsdlfhslhdslkdjfsldejfdsl@sldfhglsdfhg
      - POSTGRES_DB=netbaan_sharif
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    restart: always
    networks:
      - main
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=netbaan_sharif
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345678
    networks:
      - main
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - data:/var/lib/postgresql/_data

networks:
  main:
    name: main
volumes:
  data:

