# Generated by Django 5.1.1 on 2024-09-18 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
