# Generated by Django 5.1.1 on 2024-09-18 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_remove_users_phone_number_users_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='users',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_permissions',
        ),
    ]
